apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /pv001
    server: 10.244.0.1
  persistentVolumeReclaimPolicy: Recycle
