parameters:
 baseplan: kcli_plan.yml
 kubevirt_version: latest
 cdi_version: latest
 ui_version: latest

kubevirt:
 template: {{ template }}
 numcpus: 2
 memory: 16144
 domain: {{ domain }}
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
  - kubevirt_ui.yml
{% if nfs %}
  - path: /root/nfs.yml
    origin: nfs.yml
  - path: /root/nfs.sh
    origin: nfs.sh
{% endif %}
  - ocp_on_kubevirt.sh
  - vm_ocp_on_kubevirt.yml
 scripts: 
  - pre.sh
  - kubernetes.sh
  - dashboard.sh
  - kubevirt.sh
  - cdi.sh
  - kubevirt_ui.sh
  - vm_ocp_on_kubevirt.sh
