apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kubevirt-web-ui
    openshift.io/deployment-config.name: kubevirt-web-ui
  name: web
spec:
  replicas: 1
  selector:
    app: kubevirt-web-ui
    deployment: kubevirt-web-ui
    deploymentconfig: kubevirt-web-ui
  template:
    metadata:
      labels:
        app: kubevirt-web-ui
        deployment: kubevirt-web-ui
        deploymentconfig: kubevirt-web-ui
    spec:
      containers:
        - image: quay.io/kubevirt/kubevirt-web-ui:{{ ui_version }}
          imagePullPolicy: IfNotPresent
          name: kubevirt-web-ui
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: ui
      serviceAccountName: ui
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubevirt-web-ui
  name: web
spec:
  ports:
    - name: https
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    deploymentconfig: kubevirt-web-ui
  sessionAffinity: None
  type: ClusterIP
