parameters:
 nodes: 1
 domain: karmalabs.com
 template: CentOS-7-x86_64-GenericCloud.qcow2
 pool: default
 prefix: "ku"
 deploy_app: false
 skydive: false
 dashboard: true
 nfs: true
 sdn: flannel
 k8s_version: 1.13.4
 flannel_version: master
 multus: true
 master_memory: 6144
 node_memory: 4096
 notifycmd: "kubectl get pod --all-namespaces"
 feature_gates: CSIBlockVolume=true
 rook: false
 rook_disk_size: 20

{{prefix}}master:
 template: {{ template }}
 numcpus: 2
 memory: {{ master_memory }}
 reservedns: true
 sharedkey: true
 domain: {{ domain }}
 notifycmd: {{ notifycmd }}
 notify: true
 nets:
  - default
 disks:
  - size: 50
{% if rook %}
  - size: {{ rook_disk_size }}
{% endif %}
 pool: {{ pool }}
 files:
{% if type == 'ovirt' %}
  - ovirt_fix.sh
{% endif %}
  - join.yml
  - config.yml
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
{% if nfs %}
  - nfs.yml
  - nfs.sh
{% endif %}
{% if multus %}
  - multus.yml
  - cni-plugins.yml
  - l2-bridge.yml
{% endif %}
{% if rook %}
  - rook_pool.yml
  - rook_sc.yml
  - rook_secret.yml
  - rook.sh
{% endif %}
 scripts: 
{% if 'xenial' in template or 'yaketty' in template or 'zesty' in template or 'artful' in template or 'bionic' in template or 'cosmic' in template %}
  - pre_ubuntu.sh
{% else %}
  - pre.sh
{% endif %}
  - kubernetes.sh
{% if dashboard %}
  - dashboard.sh
{% endif %}
{% if multus %}
  - multus.sh
{% endif %}
{% if deploy_app %}
  - app.sh
{% endif %}
  - heapster.sh
{% if skydive %}
  - skydive.sh
{% endif %}
{% if nfs %}
  - nfs.sh
{% endif %}
{% if rook %}
  - install_rook.sh
{% endif %}

{% if nodes > 0 %}
{% for number in range(0, nodes) %}
{{prefix }}node0{{ number + 1 }}:
 template: {{ template }}
 numcpus: 2
 memory: {{ node_memory }}
 reservedns: true
 sharedkey: true
 domain: {{ domain }}
 nets:
  - default
 disks:
  - size: 50
{% if rook %}
  - size: {{ rook_disk_size }}
{% endif %}
 pool: {{ pool }}
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
 scripts: 
{% if 'xenial' in template or 'yaketty' in template or 'zesty' in template or 'artful' in template or 'bionic' in template or 'cosmic' in template %}
  - pre_ubuntu.sh
{% else %}
  - pre.sh
{% endif %}
{% endfor %}
{% endif %}
