parameters:
 domain: karmalabs.com
 template: centos-7
 kubevirt_version: v0.5.0
 nodes: 0

kubevirt:
 template: {{ template }}
 numcpus: 2
 memory: 8192
 domain: {{ domain }}
 nets:
  - name: default
    ip: 10.132.15.253
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
  - path: /root/kube-flannel.yml
    origin: kube-flannel.yml
  - path: /root/kube-flannel-rbac.yml
    origin: kube-flannel-rbac.yml
  - path: /root/vm.yml
    origin: vm.yml
  - path: /root/nfs.yml
    origin: nfs.yml
  - path: /root/nfs.sh
    origin: nfs.sh
 scripts: 
  - pre.sh
  - master.sh
  - heapster.sh
  - dashboard.sh
  - kubevirt.sh
