apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  replicas: 3
  endpointPublishingStrategy:
    type: HostNetwork
  nodePlacement:
    nodeSelector:
      node-role.kubernetes.io/master: ""
