---
kind: Pod
apiVersion: v1
metadata:
  name: coredns
  namespace: openshift-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-coredns
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  containers:
  - name: coredns
    securityContext:
      privileged: true
    image: quay.io/openshift-metal3/coredns-mdns:latest
    args:
    - "--conf"
    - "/etc/coredns/Corefile"
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
