---
kind: Pod
apiVersion: v1
metadata:
  name: dnsmasq
  namespace: openshift-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-dnsmasq
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  containers:
  - name: dnsmasq
    securityContext:
      privileged: true
    image: docker.io/andyshinn/dnsmasq:latest
    command:
    - /usr/sbin/dnsmasq
    args:
    - "-k"
    - "-C"
    - "/etc/dnsmasq/dnsmasq.conf"
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/dnsmasq"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
