apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autoapprover
  namespace: openshift-infra
spec:
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        spec:
          containers:
          - command:
            - "/bin/sh"
            - "-c"
            - |
              #!/bin/sh
              ( kubectl get csr -o name | xargs kubectl certificate approve ) || true
            image: docker.io/karmab/kubectl
            imagePullPolicy: Always
            name: autoapprover
          restartPolicy: OnFailure
          serviceAccountName: autoapprover
  schedule: '*/5 * * * *'
