apiVersion: v1
baseDomain: DOMAIN
compute:
- name: worker
  replicas: WORKERS
controlPlane:
  name: master
  replicas: MASTERS
metadata:
  name: CLUSTER
networking:
  clusterNetworks:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: 'PULLSECRET'
sshKey: |
    PUBKEY
